namespace GenesisNova.Inference;

/// <summary>
/// A structured query generated by the neural model to interact with the platonic space.
/// 
/// Instead of directly predicting output, the model learns to ask: "What operation?"
/// "What operands?" and "What do I predict?" The executor then handles these queries.
/// </summary>
public record PlatonicQuery(
    /// <summary>Neural model's embedding of the operation it thinks should happen.</summary>
    double[] OperationEmbedding,
    
    /// <summary>Confidence that this operation is correct (0-1).</summary>
    double OperationConfidence,
    
    /// <summary>Which tokens/positions in the input are operands (attention mask).</summary>
    bool[] OperandMask,
    
    /// <summary>For each selected operand, the model's embedding of it.</summary>
    double[][] OperandEmbeddings,
    
    /// <summary>Model's best prediction for the result embedding (before KNN lookup).</summary>
    double[] PredictedResultEmbedding,
    
    /// <summary>Raw logits for the operation head (for debugging).</summary>
    float[]? OperationLogits = null,
    
    /// <summary>For each token, the attention weight to that token (for visualization).</summary>
    double[]? OperandAttentionWeights = null);

/// <summary>
/// Result of executing a platonic query on the symbolic space.
/// </summary>
public record PlatonicQueryResult(
    /// <summary>The actual operation found in the platonic space.</summary>
    string OperationName,
    
    /// <summary>Confidence that the operation lookup succeeded (0-1).</summary>
    double OperationLookupConfidence,
    
    /// <summary>The actual operand symbols found.</summary>
    string[] ActualOperands,
    
    /// <summary>Confidence in each operand match (0-1).</summary>
    double[] OperandConfidences,
    
    /// <summary>The predicted result symbol.</summary>
    string PredictedSymbol,
    
    /// <summary>Confidence in the prediction (0-1).</summary>
    double PredictionConfidence,
    
    /// <summary>Whether symbolic verification passed (output is consistent with graph).</summary>
    bool SymbolicVerified,
    
    /// <summary>If verification failed, why.</summary>
    string? VerificationFailureReason = null);
