using System.Collections.Generic;

namespace GenesisNova.Train;

public sealed record GenesisAutonomousTrainingRequest(
    int MaxRounds = 12,
    int InitialSampleCount = 1,
    int InitialDifficulty = 0,
    int InitialEpochs = 1,
    int InitialTrainCount = 1,
    double LossThreshold = 1.2,
    int MinSampleCount = 1,
    int MaxSampleCount = 128,
    int MinTrainCount = 1,
    int MaxTrainCount = 8,
    int MaxDifficulty = 8,
    int SignalWindow = 4,
    int DifficultyStepUp = 1,
    int DifficultyStepDown = 1,
    int SampleStepUp = 1,
    int SampleStepDown = 1,
    int TrainStepUp = 1,
    int TrainStepDown = 1,
    double TrainRegressionDelta = 0.05,
    double RegressLossMultiplier = 1.25,
    double RegressTokenLossThreshold = 0.15,
    double RegressSpaceNoiseThreshold = 0.45,
    double RegressContradictionThreshold = 0.35,
    double AntiStreakPriorityWindow = 0.75,
    double NewCreatorLossMultiplier = 1.2,
    double NewCreatorBasePriority = 2.5,
    double NewCreatorRecentPenalty = 0.2,
    double MasteryLossMultiplier = 0.75,
    double WeaknessMin = 0.3,
    double WeaknessMax = 2.0,
    double ExplorationBase = 1.2,
    double MasteryPenalty = 2.5,
    double RegressionBoost = 0.35,
    double RecentHitPenalty = 0.9,
    double ConsecutivePenalty = 1.4,
    int RoundTrainBudget = 16,
    int MaxGenerationConcurrency = 4,
    string? PreferredCreator = null,
    IReadOnlyList<string>? EnabledCreators = null);
